using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Tests
{
    [TestClass]
    public class CTests
    {
        const int TimeLimit = 2000;
        const double RelativeError = 1e-9;

        [TestMethod, Timeout(TimeLimit)]
        public void Test1()
        {
            const string input = @"........
........
.......Q
........
..Q.....
........
.Q......
........";
            const string output = @"Q.......
....Q...
.......Q
.....Q..
..Q.....
......Q.
.Q......
...Q....";
            Tester.InOutTest(Tasks.C.Solve, input, output);
        }

        [TestMethod, Timeout(TimeLimit)]
        public void Test2()
        {
            const string input = @".....Q..
.Q......
........
........
........
Q.......
........
........";
            const string output = @"No Answer";
            Tester.InOutTest(Tasks.C.Solve, input, output);
        }
    }
}
